import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "./components/TopBar";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { CartProvider } from "./context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="google-site-verification" content="flvk1gog2uCtYEzwd6Ma9pW61QMdYXUzsrjWaqFXziw" />
      </head>
      <body className={inter.className}>
        <CartProvider>
          <TopBar />
          <Navbar />
          {/* <HeroSection /> */}
          <main className="">
            {children}
          </main>
          {/* <ReviewsSection /> */}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
