import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "./components/TopBar";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { CartProvider } from "./context/CartContext";
import Head from "next/head";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tubeviews Media is No. 1 Social Media Services Provider",
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="google-site-verification" content="8L6rNpN5l_HRBkQeyoCjI7a536HrGeOAadihAceTEnA" />
      </Head>
      <body className={inter.className}>
        <CartProvider>
          <TopBar />
          <Navbar />
          {/* <HeroSection /> */}
          <main className="">
            {children}
          </main>
          {/* <ReviewsSection /> */}
          <Footer />
        </CartProvider>

      </body>
    </html>
  );
}


